title: Igor Mytyuk
author: Igor Mytyuk
email: igor.mytyuk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm 21 and i'm working as a Full-Stack developer in an Italian company for over 
  five years. During my career i've developer important Android Applications,
  WebSites, WebServices and Windows Applications.

# social links
twitter_username: nicetomytyuk # DO NOT include the @ character, or else the build will fail!
github_username:  nicetomytyuk # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
